/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const DamageCategory = IDL.Variant({
  'foundation' : IDL.Null,
  'roof' : IDL.Null,
  'general' : IDL.Null,
  'walls' : IDL.Null,
});
export const DamageSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const DamageEntry = IDL.Record({
  'id' : IDL.Text,
  'structureId' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'recordedAt' : Time,
  'recordedBy' : IDL.Principal,
  'category' : DamageCategory,
  'severity' : DamageSeverity,
});
export const ConditionStatus = IDL.Record({
  'foundation' : IDL.Int,
  'roof' : IDL.Int,
  'walls' : IDL.Int,
});
export const Structure = IDL.Record({
  'id' : IDL.Text,
  'era' : IDL.Text,
  'name' : IDL.Text,
  'originalCondition' : ConditionStatus,
  'addedAt' : Time,
  'addedBy' : IDL.Principal,
  'location' : IDL.Text,
  'currentCondition' : ConditionStatus,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DamageSeverityCount = IDL.Record({
  'low' : IDL.Nat,
  'high' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const ImageDefect = IDL.Record({
  'id' : IDL.Text,
  'photoHash' : IDL.Text,
  'defectType' : IDL.Text,
  'structureId' : IDL.Text,
  'detectedAt' : Time,
  'description' : IDL.Text,
  'severity' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDamageEntry' : IDL.Func([DamageEntry], [], []),
  'addStructure' : IDL.Func([Structure], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDamageEntry' : IDL.Func([IDL.Text], [], []),
  'deleteImageDefectsForPhoto' : IDL.Func([IDL.Text], [], []),
  'deleteStructure' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDamageEntry' : IDL.Func([IDL.Text], [DamageEntry], ['query']),
  'getDamageSummary' : IDL.Func([IDL.Text], [DamageSeverityCount], ['query']),
  'getImageDefectsByPhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ImageDefect)],
      ['query'],
    ),
  'getImageDefectsByStructure' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ImageDefect)],
      ['query'],
    ),
  'getPreservationRecommendations' : IDL.Func(
      [DamageCategory],
      [IDL.Text],
      ['query'],
    ),
  'getStructure' : IDL.Func([IDL.Text], [Structure], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDamageEntriesByStructure' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DamageEntry)],
      ['query'],
    ),
  'listStructures' : IDL.Func([], [IDL.Vec(Structure)], ['query']),
  'listStructuresByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Structure)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveImageDefects' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ImageDefect)],
      [],
      [],
    ),
  'updateDamageEntry' : IDL.Func([DamageEntry], [], []),
  'updateStructure' : IDL.Func([Structure], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const DamageCategory = IDL.Variant({
    'foundation' : IDL.Null,
    'roof' : IDL.Null,
    'general' : IDL.Null,
    'walls' : IDL.Null,
  });
  const DamageSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DamageEntry = IDL.Record({
    'id' : IDL.Text,
    'structureId' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'recordedAt' : Time,
    'recordedBy' : IDL.Principal,
    'category' : DamageCategory,
    'severity' : DamageSeverity,
  });
  const ConditionStatus = IDL.Record({
    'foundation' : IDL.Int,
    'roof' : IDL.Int,
    'walls' : IDL.Int,
  });
  const Structure = IDL.Record({
    'id' : IDL.Text,
    'era' : IDL.Text,
    'name' : IDL.Text,
    'originalCondition' : ConditionStatus,
    'addedAt' : Time,
    'addedBy' : IDL.Principal,
    'location' : IDL.Text,
    'currentCondition' : ConditionStatus,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DamageSeverityCount = IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const ImageDefect = IDL.Record({
    'id' : IDL.Text,
    'photoHash' : IDL.Text,
    'defectType' : IDL.Text,
    'structureId' : IDL.Text,
    'detectedAt' : Time,
    'description' : IDL.Text,
    'severity' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDamageEntry' : IDL.Func([DamageEntry], [], []),
    'addStructure' : IDL.Func([Structure], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDamageEntry' : IDL.Func([IDL.Text], [], []),
    'deleteImageDefectsForPhoto' : IDL.Func([IDL.Text], [], []),
    'deleteStructure' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDamageEntry' : IDL.Func([IDL.Text], [DamageEntry], ['query']),
    'getDamageSummary' : IDL.Func([IDL.Text], [DamageSeverityCount], ['query']),
    'getImageDefectsByPhoto' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ImageDefect)],
        ['query'],
      ),
    'getImageDefectsByStructure' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ImageDefect)],
        ['query'],
      ),
    'getPreservationRecommendations' : IDL.Func(
        [DamageCategory],
        [IDL.Text],
        ['query'],
      ),
    'getStructure' : IDL.Func([IDL.Text], [Structure], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDamageEntriesByStructure' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DamageEntry)],
        ['query'],
      ),
    'listStructures' : IDL.Func([], [IDL.Vec(Structure)], ['query']),
    'listStructuresByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Structure)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveImageDefects' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ImageDefect)],
        [],
        [],
      ),
    'updateDamageEntry' : IDL.Func([DamageEntry], [], []),
    'updateStructure' : IDL.Func([Structure], [], []),
  });
};

export const init = ({ IDL }) => { return []; };