/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConditionStatus {
  'foundation' : bigint,
  'roof' : bigint,
  'walls' : bigint,
}
export type DamageCategory = { 'foundation' : null } |
  { 'roof' : null } |
  { 'general' : null } |
  { 'walls' : null };
export interface DamageEntry {
  'id' : string,
  'structureId' : string,
  'date' : Time,
  'description' : string,
  'recordedAt' : Time,
  'recordedBy' : Principal,
  'category' : DamageCategory,
  'severity' : DamageSeverity,
}
export type DamageSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface DamageSeverityCount {
  'low' : bigint,
  'high' : bigint,
  'medium' : bigint,
}
export interface ImageDefect {
  'id' : string,
  'photoHash' : string,
  'defectType' : string,
  'structureId' : string,
  'detectedAt' : Time,
  'description' : string,
  'severity' : string,
}
export interface Structure {
  'id' : string,
  'era' : string,
  'name' : string,
  'originalCondition' : ConditionStatus,
  'addedAt' : Time,
  'addedBy' : Principal,
  'location' : string,
  'currentCondition' : ConditionStatus,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDamageEntry' : ActorMethod<[DamageEntry], undefined>,
  'addStructure' : ActorMethod<[Structure], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDamageEntry' : ActorMethod<[string], undefined>,
  'deleteImageDefectsForPhoto' : ActorMethod<[string], undefined>,
  'deleteStructure' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDamageEntry' : ActorMethod<[string], DamageEntry>,
  'getDamageSummary' : ActorMethod<[string], DamageSeverityCount>,
  'getImageDefectsByPhoto' : ActorMethod<[string], Array<ImageDefect>>,
  'getImageDefectsByStructure' : ActorMethod<[string], Array<ImageDefect>>,
  'getPreservationRecommendations' : ActorMethod<[DamageCategory], string>,
  'getStructure' : ActorMethod<[string], Structure>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDamageEntriesByStructure' : ActorMethod<[string], Array<DamageEntry>>,
  'listStructures' : ActorMethod<[], Array<Structure>>,
  'listStructuresByLocation' : ActorMethod<[string], Array<Structure>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveImageDefects' : ActorMethod<
    [string, string, Array<ImageDefect>],
    undefined
  >,
  'updateDamageEntry' : ActorMethod<[DamageEntry], undefined>,
  'updateStructure' : ActorMethod<[Structure], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];